app/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from tomcookery.app.views import *
from tomcookery.app.models import *
from django.views.generic.simple import direct_to_template
import os


urlpatterns = patterns('tomcookery.app.views',
	#landing pages
    (r'^$', 'index'),
    (r'^leaders/$',current_leaders,{"mtitle":"Best Overall Recipe"}),
    (r'^leaders/theme-use/$',current_leaders,{"order":"-votes_theme","mtitle":"Best use of Theme"}),
    (r'^leaders/ingredient-use/$',current_leaders,{"order":"-votes_ing","mtitle":"Best use of Ingredient"}),
    #(r'^leaders/custom$',current_leaders,{"order":""}),
    (r'^themes/$',past_themes),
    (r'^themes/theme/(?P<theme_url>[a-zA-Z0-9_.-]+)/$',theme_history),
    (r'^tag/([^\s]+)/$',tag_page,{"model":Tag}),
    (r'^tag/$',tag_cloud_page,{"model":Tag,"urlParent":"tag","stitle":"Tags"}),
    (r'^ingredients/([^\s]+)/$',tag_page,{"model":Ingredient}),
    (r'^ingredients/$',tag_cloud_page,{"model":Ingredient,"urlParent":"ingredients","stitle":"Ingredients"}),
    #search
    (r'^search/$',search_page),
    #recipe voting
    (r'^vote/','recipe_vote'),
    (r'^recipes/recipe/(?P<recipe_url>[a-zA-Z0-9_.-]+)/$', 'recipe'),
    (r'^submit/$', 'submit'),
    #ajax calls
    (r'^ajax/tag/autocomplete/$', 'ajax_tag_autocompletion'),
    (r'^ajax/ingredient/autocomplete/$', 'ajax_ingredient_autocompletion'),
    #avatar
    (r'^avatar/', include('avatar.urls')),
)

urlpatterns += patterns('',
	#media path
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,'show_indexes': True}),
    #comments
    (r'^comments/',include('django.contrib.comments.urls')),
)

APP_ROOT = os.path.dirname(os.path.realpath(__file__))
urlpatterns += patterns('',
    (r'^css/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': APP_ROOT + '/CSS'}),
    (r'^css/images$', 'django.views.static.serve',
        {'document_root': APP_ROOT + '/CSS/images'}),
    (r'^js/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': APP_ROOT + '/js'}),
    (r'^admin-media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(settings.MEDIA_ROOT, 'photos')}),
)

profiles/urls.py
"""
URLConf for Django user profile management.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/profiles/'.

If the default behavior of the profile views is acceptable to you,
simply use a line like this in your root URLConf to set up the default
URLs for profiles::

    (r'^profiles/', include('profiles.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to keep the name ``profiles_profile_detail`` for the pattern
which points to the ``profile_detail`` view, since several views use
``reverse()`` with that name to generate a default post-submission
redirect. If you don't use that name, remember to explicitly pass
``success_url`` to those views.

"""

from django.conf.urls.defaults import *

from profiles import views


urlpatterns = patterns('',
	url(r'^create/$',
	   views.create_profile,
	   name='profiles_create_profile'),
	url(r'^edit/$',
	   views.edit_profile,
	   name='profiles_edit_profile'),
	url(r'^(?P<username>\w+)/$',
	   views.profile_detail,
	   name='profiles_profile_detail'),
	url(r'^$',
	   views.profile_list,
	   name='profiles_profile_list'),

	
)

urls.py
from django.conf.urls.defaults import *
from tomcookery.app.forms import editProfile
from tomcookery.app.models import createUserProfile

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    #profile pages
    ('^profiles/edit', 'profiles.views.edit_profile', {'form_class': editProfile,}),
    ('^profiles/create', 'profiles.views.create_profile', {'form_class': editProfile,}),
    (r'^profiles/', include('profiles.urls')),
    url( r'^accounts/register/$',      'registration.views.register',
        { 'profile_callback': createUserProfile }, name = 'registration_register' ),
    (r'^accounts/', include('registration.urls')),
    (r'', include('app.urls')),
    
)

app/forms.py
from django import forms
import re
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from tomcookery.app.models import *

difficultyChoice = (('-','Please Select'),('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult'))
courseChoice = (('-','Please Select'),('Appetizer', 'Appetizer'), ('Breakfast', 'Breakfast'), ('Dessert','Dessert'),('Entree','Entree'),('Lunch', 'Lunch'), ('Salad', 'Salad'), ('Soup', 'Soup'), ('Snack', 'Snack'))


class recipeNewSaveForm(forms.Form):
	name = forms.CharField(
	label=u'Name',
	widget=forms.TextInput(attrs={'size': 64, 'class':'required'})
	)
	ingredients = forms.CharField(
	required=True,
	widget=forms.HiddenInput(attrs={ 'class':'required'})
	) 
	
	summary = forms.CharField(
	widget=forms.Textarea(attrs={ 'class':'required'})
	)
	
	instructions = forms.CharField(
	label=u'Instructions',
	widget=forms.Textarea(attrs={ 'class':'required'})
	)
	
	photo=forms.ImageField(required=False)
	
	yields = forms.CharField(
	label=u'Number of servings?',
	required=False,
	widget=forms.TextInput(attrs={'size': 4})
	)
	
	durations = forms.CharField(
	required=False,
	widget=forms.TextInput(attrs={'size':4})
	)
	
	difficulty = forms.ChoiceField(
	required=True,
	widget=forms.Select(attrs={ 'class':'required'}),
	choices=difficultyChoice,
	)
	
	course = forms.ChoiceField(
	required=True,
	widget=forms.Select(attrs={ 'class':'required'}),
	choices=courseChoice,
	)
	
	tags = forms.CharField(
	label=u'Tags',
	widget=forms.TextInput(attrs={'size': 64, "placeholder":"e.g. thai, curry, easy",'class':'required'})
	)

class editProfile(ModelForm):
	class Meta:
		model=MyProfile
		exclude = ('recipePoints','commentPoints','votePoints','recipeLiked','chefRank','user','users_voted_ing','users_voted_overall','users_voted_theme')

class searchForm(forms.Form):
	query = forms.CharField(
		label=u'Enter a keyword to search for',
		widget = forms.TextInput(attrs={'size':32})
		)

profiles/views.py
"""
Views for creating, editing and viewing site-specific user profiles.

"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.list_detail import object_list

from profiles import utils


def create_profile(request, form_class=None, success_url=None,
                   template_name='create_profile.html',
                   extra_context=None):
    """
    Create a profile for the current user, if one doesn't already
    exist.
    
    If the user already has a profile, as determined by
    ``request.user.get_profile()``, a redirect will be issued to the
    :view:`profiles.views.edit_profile` view. If no profile model has
    been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    **Optional arguments:**
    
    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and creating the user
        profile. This form class must define a method named
        ``save()``, implementing the same argument signature as the
        ``save()`` method of a standard Django ``ModelForm`` (this
        view will call ``save(commit=False)`` to obtain the profile
        object, and fill in the user before the final save). If the
        profile object includes many-to-many relations, the convention
        established by ``ModelForm`` of using a method named
        ``save_m2m()`` will be used, and so your form class should
        also define this method.
        
        If this argument is not supplied, this view will use a
        ``ModelForm`` automatically generated from the model specified
        by ``AUTH_PROFILE_MODULE``.
    
    ``success_url``
        The URL to redirect to after successful profile creation. If
        this argument is not supplied, this will default to the URL of
        :view:`profiles.views.profile_detail` for the newly-created
        profile object.
    
    ``template_name``
        The template to use when displaying the profile-creation
        form. If not supplied, this will default to
        :template:`profiles/create_profile.html`.
    
    **Context:**
    
    ``form``
        The profile-creation form.
    
    **Template:**
    
    ``template_name`` keyword argument, or
    :template:`profiles/create_profile.html`.
    
    """
    try:
        profile_obj = request.user.get_profile()
        return HttpResponseRedirect(reverse('profiles_edit_profile'))
    except ObjectDoesNotExist:
        pass
    
    #
    # We set up success_url here, rather than as the default value for
    # the argument. Trying to do it as the argument's default would
    # mean evaluating the call to reverse() at the time this module is
    # first imported, which introduces a circular dependency: to
    # perform the reverse lookup we need access to profiles/urls.py,
    # but profiles/urls.py in turn imports this module.
    #
    
    if success_url is None:
        success_url = reverse('profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    if form_class is None:
        form_class = utils.get_profile_form()
    if request.method == 'POST':
        form = form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            profile_obj = form.save(commit=False)
            profile_obj.user = request.user
            profile_obj.save()
            if hasattr(form, 'save_m2m'):
                form.save_m2m()
            return HttpResponseRedirect(success_url)
    else:
        form = form_class()
    
    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value
    
    return render_to_response(template_name,
                              { 'form': form },
                              context_instance=context)
create_profile = login_required(create_profile)

def edit_profile(request, form_class=None, success_url=None,
                 template_name='edit_profile.html',
                 extra_context=None):
    """
    Edit the current user's profile.
    
    If the user does not already have a profile (as determined by
    ``User.get_profile()``), a redirect will be issued to the
    :view:`profiles.views.create_profile` view; if no profile model
    has been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    **Optional arguments:**
    
    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and editing the user
        profile. This form class must operate similarly to a standard
        Django ``ModelForm`` in that it must accept an instance of the
        object to be edited as the keyword argument ``instance`` to
        its constructor, and it must implement a method named
        ``save()`` which will save the updates to the object. If this
        argument is not specified, this view will use a ``ModelForm``
        generated from the model specified in the
        ``AUTH_PROFILE_MODULE`` setting.
    
    ``success_url``
        The URL to redirect to following a successful edit. If not
        specified, this will default to the URL of
        :view:`profiles.views.profile_detail` for the profile object
        being edited.
    
    ``template_name``
        The template to use when displaying the profile-editing
        form. If not specified, this will default to
        :template:`profiles/edit_profile.html`.
    
    **Context:**
    
    ``form``
        The form for editing the profile.
        
    ``profile``
         The user's current profile.
    
    **Template:**
    
    ``template_name`` keyword argument or
    :template:`profiles/edit_profile.html`.
    
    """
    try:
        profile_obj = request.user.get_profile()
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/')
    
    #
    # See the comment in create_profile() for discussion of why
    # success_url is set up here, rather than as a default value for
    # the argument.
    #
    
    if success_url is None:
        success_url = reverse('profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    if form_class is None:
        form_class = utils.get_profile_form()
    if request.method == 'POST':
        form = form_class(data=request.POST, files=request.FILES, instance=profile_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(success_url)
    else:
        form = form_class(instance=profile_obj)
    
    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value

    return render_to_response(template_name,
                              { 'form': form,
                                'profile': profile_obj, },
                              context_instance=context)
edit_profile = login_required(edit_profile)

def profile_detail(request, username, public_profile_field=None,
                   template_name='profile_detail.html',
                   extra_context=None):
    """
    Detail view of a user's profile.
    
    If no profile model has been specified in the
    ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    If the user has not yet created a profile, ``Http404`` will be
    raised.
    
    **Required arguments:**
    
    ``username``
        The username of the user whose profile is being displayed.
    
    **Optional arguments:**

    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``public_profile_field``
        The name of a ``BooleanField`` on the profile model; if the
        value of that field on the user's profile is ``False``, the
        ``profile`` variable in the template will be ``None``. Use
        this feature to allow users to mark their profiles as not
        being publicly viewable.
        
        If this argument is not specified, it will be assumed that all
        users' profiles are publicly viewable.
    
    ``template_name``
        The name of the template to use for displaying the profile. If
        not specified, this will default to
        :template:`profiles/profile_detail.html`.
    
    **Context:**
    
    ``profile``
        The user's profile, or ``None`` if the user's profile is not
        publicly viewable (see the description of
        ``public_profile_field`` above).
    
    **Template:**
    
    ``template_name`` keyword argument or
    :template:`profiles/profile_detail.html`.
    
    """
    user = get_object_or_404(User, username=username)
    try:
        profile_obj = user.get_profile()
    except ObjectDoesNotExist:
        raise Http404
    if public_profile_field is not None and \
       not getattr(profile_obj, public_profile_field):

app/templates/feature_recipe_snippet.html
<section class="featured recipe_list hfeed">
    {% if recipes|length > 0 %}
    	{% load thumbnail %}
    	<h1 class='section-title'>{{ sectiontitle }} {{sectiontitlesplit}}  Recipe</h1>
        {% for recipe in recipes %}
        <article class="hentry {% if recipe.photos.all|length > 0 %}w-images{% else %}n-images{% endif %}">
            {% for photo in recipe.photos.all|slice:":1" %}
                {% thumbnail photo.photo "150x150" crop="center" as im %}
               <a href="{{ recipe.get_absolute_url }}" title="{{ recipe.name }}" class="fn" rel="bookmark"><img src="{{ im.url }}" alt="{{ recipe.name }}" width="{{ im.width }}" height="{{ im.height }}" class="photo"/></a>
               {% endthumbnail %}
            {% endfor %}
            <span class="content">
            
            <h2 class="entry-title"><a href="{{ recipe.get_absolute_url }}" title="{{ recipe.name }}" class="bookmark" rel="bookmark">{{ recipe.name }} </a> {% include "vote.html" with votingOpen=recipe.votingOpen %}</h2>
            <p class="author">{{recipe.submitor.get_profile.chefRank.name }}: <a href="/profiles/{{recipe.submitor.username}}" title="link to profile page" class="userName">{{recipe.submitor.username}}'s</a></p>
            
            <p class="entry-summary">{{ recipe.summary|truncatewords:50 }}</p>
            {% include "tags_snippet.html" %}
            </span>
        </article>
        {% endfor %}
    {% else %}
        <h3 class="empty-search">No recipes found.</h3>
    {% endif %}
</section>

app/templates/nav.html
<nav>

	<ul>
		<li><a href="/" title="Home" class="" rel="bookmark">Home</a></li>
		{% if currentTheme %}
		<li><a href="/leaders" title="Home" class="" rel="bookmark">Overall Leaders</a></li>
		<li><a href="/leaders/ingredient-use/" title="Home" class="" rel="bookmark">Ingredient Leaders</a></li>
		<li><a href="/leaders/theme-use/" title="Home" class="" rel="bookmark">Theme Use Leaders</a></li>
		{% endif %}
		<li><a href="/themes" title="Past Themes" class="" rel="bookmark">Past Themes</a></li>
	</ul>

</nav>

app/templates/pastthemes.html
{% extends "base.html" %}
{%block pageId%}themes{%endblock pageId%}
{% block content %}

{% include "themes_snippet.html" with sectiontitle="Past Themes" showImages="True" %}
{% endblock %}
{% block rightColumn %}
{% include "standard-right-column.html" %}
{% endblock rightColumn %}

app/templates/recipe_score.html
<table class="score">
	<caption><h3>Recipe Votes:</h3></caption>
	<tr>
	<th><h3>Overall</h3></th>
	<th><h3>Ingredient</h3></th>                  		
	<th><h3>Theme Use</h3></th>
	</tr>
	<tr>
	<td>{{ recipe.votes }}</td>
	<td>{{ recipe.votes_ing }}</td>
	<td>{{ recipe.votes_theme }}</td>
	</tr>
</table>

app/templates/recipes.html
{# The recipes list page #}
{% extends "base.html" %}
{% block title %}{{ block.super }} - Recipes{% endblock %}
{% block content %}
{% include "recipes_snippet.html" %}
{% endblock  %}
{% block rightColumn %}
{% include "standard-right-column.html" %}
{% endblock rightColumn %}

app/templates/search.html
{% extends "base.html" %}
{% block external %}
<script>
$(document).ready(function(){
	var query = $("#id_query").val();
	$("#search-results").load(
		"/search/?ajax&query="+ encodeURIComponent(query)
		);
	return false;
});
</script>
{% endblock %}
{% block title %}Search Recipes{% endblock %}

{% block content %}
  <form id="search-form" method="get" action=".">
  	{{ form.as_p }}
  	<input type="submit" value="search" />
  </form>
  <div id="search-results">
  	{% if show_results %}
  		{% include "recipes_snippet.html" %}
  	{% endif %}
  </div>
{% endblock %}

app/templates/standard-right-column.html
    	<aside id="standard-sidebar">
    		{% include "user_info_snippet.html" %}
			<form id="search" method="get" action="/search">
				<fieldset>
					<div><input name="query" type="search" placeholder="Find Recipes"></div>
					<input type="submit" value="search" />
				</fieldset>
			</form>
			
    		{% include "recipes_snippet.html" with recipes=leadingRecipes sectiontitle="Current Leaders" %}    		
    	</aside>

app/templates/submit.html
{# The recipe submission page #}
{# A single recipe page #}

{% extends "base.html" %}
{% block title %}Recipe Submit{% endblock %}
{%block pageId%}submit{%endblock%}
{% block content %}
	<section id="upload-form" class="content">
		{% if submissionsOpen %}
		{% if user.is_authenticated %}
		
			<form id="new-recipe" name="new-recipe" action="." method="POST"enctype="multipart/form-data">
				<h1 id="instructions">Enlist your recipe in the {{currentTheme.name}} war!</h1>
				<div id="form-messages">
				{% if form.errors %}
					<h2><strong>Button Up Soldier!</strong> Your recipe is not ship shape!</h2> 
				    <ul>
				    {% for error in form.errors %}
				        <li><strong>{{ error|escape }}</strong></li>
				    {% endfor %}
				    </ul>
				{% endif %}
				</div>
				{% csrf_token %}
				<fieldset>
				<div>
		        	<label for="id_name">Recipe Name:<abbr class="required">*</abbr></label>
		        	{{ form.name }}
		       	</div>
		       	<div>
					<label for="id_durations">Recipe Difficulty:<abbr class="required">*</abbr></label>
					{{ form.difficulty }}
				</div>
				<div>
					<label for="id_durations">Recipe Course:<abbr class="required">*</abbr></label>
					{{ form.course }}
				</div>
				<div>
		        	<label for="id_name">Use of Theme and Ingredient:<abbr class="required">*</abbr></label>
		        	{{ form.summary }}
		       	</div>
				<fieldset id="ingredients-list">
					<legend>Ingredients<abbr class="required">*</abbr></legend>
					<div id="ingredientWrap">
						<div class="ingredientEntry">
							<label for="measurement" class="how-much">Amount:</label>
							<input type="text" class="measurement" placeholder="e.g. 1 tbsp" />
							<label for="ingredient" class="what">Ingredient:</label>
							<input type="text" class="ingredient" placeholder="e.g. salt" />
						</div>
					</div>
					<button id="add-another">+ Add another ingredient</button>
					{{ form.ingredients }}		
				</fieldset>

				<div>
					<label for="id_instructions">Cooking Directions:<abbr class="required">*</abbr></label>
					{{ form.instructions }}
				</div>
				<div>	
					<label for="picture">Image:</label>
					{{ form.photo }}
				</div>
				<div>	
					<label for="id_yields">Number of servings:</label>
					{{ form.yields }}
				</div>
				<div>
					<label for="id_durations">Total time required:</label>
					{{ form.durations }}
				</div>
				<div>
					<label for="id_tags">How would you describe this recipe?<abbr class="required">*</abbr></label>
					{{ form.tags }}
					<em class="note">Seperate tags with commas e.g. spicy,italian</em>
				</div>
				<div class="controls">
				<input type="submit" value="Submit your recipe">
				</div>
				<fieldset>
			</form>
		{% else %}
			<script>
				window.location("/accounts/login");
			</script>
		{% endif%}
		{% else %}
			<h1>Sorry, recipe submission is currently closed. But you can prepare for the next battle.
		{% endif %}
	</section>
{% endblock %}
{% block rightColumn %}
{% endblock rightColumn %}
 <!--Right Column Article Template-->

{% block jsincludes %}
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.8.1/jquery.validate.js"></script>

{% endblock %}
{% block javaScript %}

$("#add-another").click(function(){
	var ingrhtml = $("#ingredientWrap .ingredientEntry:first").clone();
	ingrhtml.find(".measurement,.ingredient").val("")
	$("#ingredientWrap").append(ingrhtml);
	return false;
});

$("#new-recipe").submit(function(){
	var sl = $("#ingredientWrap .ingredientEntry")
	var ingJson = []
	sl.each(function(){
		var el = $(this);
		var ing = {
			'measurement': el.find(".measurement").val(),
			'ingredient':el.find(".ingredient").val()
			}
		ingJson.push(ing);
	});
	$("#id_ingredients").val(JSON.stringify(ingJson));
});

$(function() {
		function split( val ) {
			return val.split( /,\s*/ );
		}
		function extractLast( term ) {
			return split( term ).pop();
		}

		$( "#id_tags" )
			.bind( "keydown", function( event ) {
				// don't navigate away from the field on tab when selecting an item
				if ( event.keyCode === $.ui.keyCode.TAB &&
						$( this ).data( "autocomplete" ).menu.active ) {
					event.preventDefault();
				}
			})
			.autocomplete({
				source: function( request, response ) {
					$.getJSON( "/ajax/tag/autocomplete", {
						term: extractLast( request.term )
					}, response );
				},
				search: function() {
					// custom minLength
					var term = extractLast( this.value );
					if ( term.length < 2 ) {
						return false;
					}
				},
				focus: function() {
					// prevent value inserted on focus
					return false;
				},
				select: function( event, ui ) {
					var terms = split( this.value );
					// remove the current input
					terms.pop();
					// add the selected item
					terms.push( ui.item.value );
					// add placeholder to get the comma-and-space at the end
					terms.push( "" );
					this.value = terms.join( ", " );
					return false;
				}
			});
			
			$( "#ingredientWrap .ingredient" ).live( "focus", function(){
				$( this ).bind( "keydown", function( event ) {
					// don't navigate away from the field on tab when selecting an item
					if ( event.keyCode === $.ui.keyCode.TAB &&
							$( this ).data( "autocomplete" ).menu.active ) {
						event.preventDefault();
					}
				})
				.autocomplete({
					source: function( request, response ) {
						$.getJSON( "/ajax/ingredient/autocomplete", {
							term: extractLast( request.term )
						}, response );
					},
					focus: function() {
						// prevent value inserted on focus
						return false;
					}
				});
			})
	});

//Validation
	jQuery.validator.setDefaults({ 
		errorElement: "em",
		success: function(label) {
			label.addClass("valid");
		},
		showErrors: function(errorMap, errorList) {
			var numErrors = this.numberOfInvalids(),
				errorContainerVisible = errorContainer.is(':visible');
				
			this.defaultShowErrors();
			
			if (numErrors && errorContainerVisible) {
				errorContainer
					.html("Your form contains " + numErrors + " error" + ((numErrors == 1) ? '' : "s") + " that must be corrected before continuing")
					.show();
				$(this.currentForm).removeClass('valid');
			}
			else if (errorContainerVisible) {
				errorContainer
					.text('All errors have been corrected, please continue')
					.show();
				$(this.currentForm).addClass('valid');
			}
			else {
				errorContainer.hide();
			}
		},
	 	errorPlacement: function(error, element) {
	 		// Listed elements
			if ( (element.attr("type") == "radio") || (element.attr("type") == "checkbox") ) {
				error.insertAfter($(element).parents("ul").eq(0)).wrap("<span class=\"type-list\"></span>");
			}
			
			// Select elments
			else if (element.is("select") && $(element).parent("div.group-date").size()) {
				// Insert after last select element
				error.insertAfter($("select:last", element.parent("div.group-date")));
			}
			// All other
			else {
				error.insertAfter(element);
			}
		},
		focusInvalid: false
	});
	
	// select a placeholder for form messages
	errorContainer = $('#form-messages');
		
	// Bind event to invalid form submission
	$("div.semantic-form").parent("form").bind("invalid-form.validate", function(e, validator) {
		errorContainer.show();
		$('html,body').animate( 
			{scrollTop: $("div#form-messages").offset().top}, 1000
		);
	});
	
	// Validate on hide conditional section event
	$("div.semantic-form").parent("form").bind("clearConditionalSection", function (event, conditionalSection) {
		if ($("#form-messages:visible").size()) {
			$(this).valid();
		}
	});
	
	// Override default messages
	$.extend($.validator.messages, {  
		required : '<img src="#" alt="Error" />This information is required',
		requiredDate : "This information is required ",
		digits : "Please enter a numeric value",
	});
	
$("#new-recipe").validate();
{% endblock javaScript %}

app/templates/tag_page.html
{% extends "base.html" %}
{% block title %}Tag: {{ tag_name }}{% endblock %}
{% block content %}
	{% include "recipes_snippet.html" with sectiontitle=title %}
{% endblock %}
{% block rightColumn %}
{% include "standard-right-column.html" %}
{% endblock rightColumn %}